AY2425S1-CS2103T-T09-1/tp

docs/AboutUs.md, docs/team/jaymeson.md
- Add Jaymeson's details
- Indicate the roles played and responsibilities held by Jaymeson.
- Add Jaymeson's portfolio
=> Update About Us Page and Portfolio for Jaymeson

docs/AboutUs.md, docs/team/uniqly.md
=> Update AboutUs with Simon's info

docs/AboutUs.md, docs/team/qijun.md, docs/team/simon.md
=> Fix issues in AboutUs

build.gradle
=> Fix Gradle routing issues for Build

src/main/java/seedu/internbuddy/model/application/AppStatus.java, src/main/java/seedu/internbuddy/model/application/Application.java, src/main/java/seedu/internbuddy/model/application/Description.java, src/main/java/seedu/internbuddy/model/application/exceptions/ApplicationNotFoundException.java, src/main/java/seedu/internbuddy/model/application/exceptions/DuplicateApplicationException.java, src/test/java/seedu/internbuddy/model/application/AppStatusTest.java, src/test/java/seedu/internbuddy/model/application/ApplicationTest.java, src/test/java/seedu/internbuddy/model/application/DescriptionTest.java, src/test/java/seedu/internbuddy/testutil/ApplicationBuilder.java, src/test/java/seedu/internbuddy/testutil/TypicalApplications.java
Important info for Application class:
Fields:
- description
- status
Methods:
- setAppStatus
Other classes added:
- Description
- AppStatus
closes #56
=> Add application class

src/main/java/seedu/internbuddy/logic/commands/EditCommand.java, src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java, src/main/java/seedu/internbuddy/model/company/Company.java, src/main/java/seedu/internbuddy/model/util/SampleDataUtil.java, src/main/java/seedu/internbuddy/storage/JsonAdaptedApplication.java, src/main/java/seedu/internbuddy/storage/JsonAdaptedCompany.java, src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json, src/test/java/seedu/internbuddy/logic/LogicManagerTest.java, src/test/java/seedu/internbuddy/logic/parser/AddCommandParserTest.java, src/test/java/seedu/internbuddy/model/company/CompanyTest.java, src/test/java/seedu/internbuddy/storage/JsonAdaptedApplicationTest.java, src/test/java/seedu/internbuddy/storage/JsonAdaptedCompanyTest.java, src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java, src/test/java/seedu/internbuddy/testutil/TypicalCompanies.java
=> Add application list to `Company` and update storage

src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java, src/main/java/seedu/internbuddy/logic/parser/ParserUtil.java, src/main/java/seedu/internbuddy/model/company/Address.java, src/main/java/seedu/internbuddy/model/company/Phone.java, src/main/java/seedu/internbuddy/storage/JsonAdaptedCompany.java, src/main/java/seedu/internbuddy/ui/CompanyCard.java, src/test/java/seedu/internbuddy/logic/parser/ParserUtilTest.java, src/test/java/seedu/internbuddy/storage/JsonAdaptedCompanyTest.java, src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java, src/test/java/seedu/internbuddy/testutil/CompanyUtil.java
Resolves #65 
The app now has a way to handle optional phone number and address without resorting to a reserved string.
=> Improved handling of optional inputs

src/main/java/seedu/internbuddy/logic/Messages.java, src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java, src/main/java/seedu/internbuddy/logic/parser/AddressBookParser.java, src/main/java/seedu/internbuddy/logic/parser/DeleteCommandParser.java, src/main/java/seedu/internbuddy/logic/parser/ParserUtil.java, src/main/java/seedu/internbuddy/logic/parser/WithdrawCommandParser.java, src/test/java/seedu/internbuddy/logic/commands/WithdrawCommandTest.java, src/test/java/seedu/internbuddy/logic/parser/ParserUtilTest.java, src/test/java/seedu/internbuddy/logic/parser/WithdrawCommandParserTest.java, src/test/java/seedu/internbuddy/testutil/TypicalIndexes.java
=> Add withdraw command

docs/UserGuide.md, docs/index.md
* Fixed typos in `index.md`
* Fixed logical inconsistencies in `UserGuide.md`
Fixes #82 and Fixes #85
=> Fix typos in website

docs/index.md
=> Fix Badges in index.md

src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java, src/main/java/seedu/internbuddy/logic/commands/EditCommand.java, src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java, src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java, src/main/java/seedu/internbuddy/model/company/Company.java, src/main/java/seedu/internbuddy/storage/JsonAdaptedCompany.java, src/test/data/JsonAddressBookStorageTest/invalidAndValidCompanyAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicateCompanyAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json, src/test/java/seedu/internbuddy/storage/JsonAdaptedCompanyTest.java, src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java
Added isFavourite boolean field into Company class as well as corresponding JSON files
Closes #97
=> Add favourite field into Company class

docs/UserGuide.md, src/main/java/seedu/internbuddy/ui/CompanyListPanel.java
=> Tweak UserGuide

src/main/java/seedu/internbuddy/ui/CompanyListPanel.java
=> Add logic to display favourited companies first

docs/UserGuide.md
=> UserGuide Logo Fix

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/StorageClassDiagram.puml
=> Update DG Design section

docs/UserGuide.md, src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java, src/main/java/seedu/internbuddy/logic/parser/AddressBookParser.java, src/main/java/seedu/internbuddy/logic/parser/ApplyCommandParser.java, src/main/java/seedu/internbuddy/logic/parser/UpdateCommandParser.java, src/main/java/seedu/internbuddy/logic/parser/WithdrawCommandParser.java, src/test/java/seedu/internbuddy/logic/commands/ApplyCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/UpdateCommandTest.java, src/test/java/seedu/internbuddy/logic/parser/AddressBookParserTest.java, src/test/java/seedu/internbuddy/logic/parser/ApplyCommandParserTest.java, src/test/java/seedu/internbuddy/logic/parser/UpdateCommandParserTest.java
=> Add initial implementation of Update command

docs/DeveloperGuide.md, docs/diagrams/ApplyCommandSequence.puml, docs/diagrams/UpdateCommandSequence.puml
=> Add Apply and Update to Developer Guide

docs/UserGuide.md, src/main/java/seedu/internbuddy/logic/commands/FavCommand.java, src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java, src/main/java/seedu/internbuddy/logic/parser/AddressBookParser.java, src/main/java/seedu/internbuddy/logic/parser/FavCommandParser.java, src/main/java/seedu/internbuddy/logic/parser/UnfavCommandParser.java, src/test/java/seedu/internbuddy/logic/commands/FavCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/UnfavCommandTest.java, src/test/java/seedu/internbuddy/logic/parser/AddressBookParserTest.java, src/test/java/seedu/internbuddy/logic/parser/FavCommandParserTest.java, src/test/java/seedu/internbuddy/logic/parser/UnfavCommandParserTest.java
Added fav and unfav commands, similar to mark and unmark of IP
closes #94
=> Add Favourite and Unfavourite command

docs/DeveloperGuide.md, docs/diagrams/FindSequenceDiagram.puml, src/main/java/seedu/internbuddy/logic/commands/FindCommand.java, src/main/java/seedu/internbuddy/logic/parser/FindCommandParser.java, src/main/java/seedu/internbuddy/model/company/Company.java, src/main/java/seedu/internbuddy/model/company/NameContainsKeywordsPredicate.java, src/test/java/seedu/internbuddy/model/company/NameContainsKeywordsPredicateTest.java
Updated the user stories in our Developer Guide to reflect our new audience, which is STEM majors, rather than just CS majors
=> Change DG User Stories, add PUML and Logger

src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java, src/main/java/seedu/internbuddy/logic/commands/FavCommand.java, src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java, src/test/java/seedu/internbuddy/logic/commands/ApplyCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/FavCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/UnfavCommandTest.java
=> Change result for apply, fav and unfav command

README.md, docs/UserGuide.md
The user guide now has:
* Introduction of our product to our users
* Overview of InternBuddy
* How to use the guide
Resolves #134
=> Update UG with overview of internbuddy

docs/DeveloperGuide.md
=> Update DG with manual test cases

src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java, src/main/java/seedu/internbuddy/logic/commands/EditCommand.java, src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java, src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java, src/main/java/seedu/internbuddy/model/company/Company.java, src/main/java/seedu/internbuddy/model/company/Status.java, src/main/java/seedu/internbuddy/model/company/StatusType.java, src/main/java/seedu/internbuddy/model/util/SampleDataUtil.java, src/main/java/seedu/internbuddy/storage/JsonAdaptedCompany.java, src/main/java/seedu/internbuddy/ui/CompanyCard.java, src/test/java/seedu/internbuddy/logic/LogicManagerTest.java, src/test/java/seedu/internbuddy/logic/commands/EditCommandTest.java, src/test/java/seedu/internbuddy/logic/parser/AddCommandParserTest.java, src/test/java/seedu/internbuddy/model/company/StatusTest.java, src/test/java/seedu/internbuddy/model/company/StatusTypeTest.java, src/test/java/seedu/internbuddy/testutil/CompanyUtil.java
* Refactor `Status` to use enums
* Make results only display relevant edited field
=> EditCommand enhancements

src/main/java/seedu/internbuddy/logic/commands/EditCommand.java, src/main/java/seedu/internbuddy/logic/commands/FindCommand.java
=> Make error messages more relevant

src/main/java/seedu/internbuddy/logic/commands/DeleteCommand.java, src/test/java/seedu/internbuddy/logic/commands/DeleteCommandTest.java
Now only shows "Deleted company: <CompanyName>"
=> Change delete success message to only show name

docs/UserGuide.md
=> Fix formatting error in User Guide

docs/UserGuide.md, src/main/java/seedu/internbuddy/ui/CompanyCard.java
=> Add naming specifications to User Guide

src/main/java/seedu/internbuddy/logic/Messages.java, src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java, src/main/java/seedu/internbuddy/logic/commands/DeleteCommand.java, src/main/java/seedu/internbuddy/logic/commands/EditCommand.java, src/main/java/seedu/internbuddy/logic/commands/FavCommand.java, src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java, src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java, src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java, src/main/java/seedu/internbuddy/logic/parser/WithdrawCommandParser.java, src/main/java/seedu/internbuddy/model/application/Application.java, src/test/java/seedu/internbuddy/logic/LogicManagerTest.java, src/test/java/seedu/internbuddy/logic/commands/ApplyCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/DeleteCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/EditCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/FavCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/UnfavCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/UpdateCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/WithdrawCommandTest.java, src/test/java/seedu/internbuddy/logic/parser/WithdrawCommandParserTest.java, src/test/java/seedu/internbuddy/model/application/ApplicationTest.java
* More specific error messages relating to index (specifically size and ambiguous index)
* Users are now informed about `Status` being set to `CLOSED`
Addresses #152 and Addresses #153
=> WithdrawCommand (and index based commands) Enhancements

src/main/java/seedu/internbuddy/logic/commands/ViewCommand.java, src/test/java/seedu/internbuddy/logic/commands/DeleteCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/EditCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/ViewCommandTest.java
=> Fix compile error due to index exceed message

src/main/java/seedu/internbuddy/logic/parser/FindCommandParser.java, src/main/java/seedu/internbuddy/model/company/NameContainsKeywordsPredicate.java
Resolves #154 and #155 
* Simplified Logging by removing redundant logging calls
* Enhanced Find Command functionality by enabling partial matching and case-insensitive finding. e.g. (`find Go` or `find go` to quickly find Google instead of `find Google`)
=> Refactor and Enhance FindCommand

docs/DeveloperGuide.md, docs/diagrams/FavSequenceDiagram.puml
=> Update Developer Guide for fav and unfav feature implementations

src/main/resources/view/InternBuddyTheme.css
=> Fix 1 JavaFX warning

src/main/java/seedu/internbuddy/logic/Messages.java, src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java, src/main/java/seedu/internbuddy/logic/commands/DeleteCommand.java, src/main/java/seedu/internbuddy/logic/commands/EditCommand.java, src/main/java/seedu/internbuddy/logic/commands/FavCommand.java, src/main/java/seedu/internbuddy/logic/commands/ReopenCommand.java, src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java, src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java, src/main/java/seedu/internbuddy/logic/commands/ViewCommand.java, src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java, src/test/java/seedu/internbuddy/logic/LogicManagerTest.java, src/test/java/seedu/internbuddy/logic/commands/UpdateCommandTest.java, src/test/java/seedu/internbuddy/logic/commands/WithdrawCommandTest.java
=> Fix output message for update command & update empty lists error messages

src/main/java/seedu/internbuddy/logic/commands/AddCommand.java, src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java, src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java, src/main/java/seedu/internbuddy/logic/parser/UpdateCommandParser.java
=> Fix output errors related to AppStatus

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/ApplyCommandSequence.puml, docs/diagrams/DeleteSequenceDiagram.puml, docs/diagrams/FavSequenceDiagram.puml, docs/diagrams/FindSequenceDiagram.puml, docs/diagrams/UiClassDiagram.puml, docs/diagrams/UpdateCommandSequence.puml, docs/diagrams/ViewSequenceDiagram.puml
* #206 
* #207 
* #208 
* #209 
* #210 
* #213 
* #214 
* #216 
* #218 
* #222
=> Update User Guide and Developer Guide with better clarity and formatting

src/test/java/seedu/internbuddy/logic/parser/AddCommandParserTest.java, src/test/java/seedu/internbuddy/logic/parser/DeleteCommandParserTest.java, src/test/java/seedu/internbuddy/logic/parser/FavCommandParserTest.java, src/test/java/seedu/internbuddy/logic/parser/ReopenCommandParserTest.java, src/test/java/seedu/internbuddy/logic/parser/UnfavCommandParserTest.java, src/test/java/seedu/internbuddy/logic/parser/ViewCommandParserTest.java
=> Improve parser package test cases

docs/DeveloperGuide.md, docs/UserGuide.md, docs/_markbind/layouts/default.md
* #259 
* #231 
* #277 
* #243 
* #252 
* #270 
* #283
=> Fix hyperlinks to various APIs in Developer Guide and Updating User Guide

docs/UserGuide.md
=> Expand OA definition

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/FavSequenceDiagram.puml, docs/diagrams/ViewSequenceDiagram.puml
* #136 
* #211 
* #235 
* #242
* #246 
* #247 
* #267 
* #274
* #276
* #282
=> Various updates to DG and UG

docs/DeveloperGuide.md, docs/UserGuide.md
=> Update UG about extra parameters and DG about edit command fix

docs/UserGuide.md
=> Fix inconsistent format

docs/UserGuide.md
=> Add fav and unfav to summary table

docs/DeveloperGuide.md
=> Add error message planned enhancement

docs/diagrams/ApplyCommandSequence.puml, docs/diagrams/DeleteSequenceDiagram.puml, docs/diagrams/FavSequenceDiagram.puml, docs/diagrams/FindSequenceDiagram.puml, docs/diagrams/UpdateCommandSequence.puml, docs/diagrams/ViewSequenceDiagram.puml
This is an attempt to resolve #215
=> Update UML Diagrams with larger font sizes for better readability

docs/DeveloperGuide.md, docs/UserGuide.md
Addresses the following issues:
- #239: Added to Known Issues, not considered to be a bug since this can happen in real life
- #227: Added to Planned Enhancements
=> Add Known Issue regarding Identical Applications and Planned Enhancement regarding Company Status

docs/DeveloperGuide.md, docs/UserGuide.md
Reformatted some sections to it more pleasant to use
=> Clean up user guide for submission

docs/UserGuide.md, src/main/java/seedu/internbuddy/logic/commands/ViewCommand.java, src/main/java/seedu/internbuddy/logic/parser/ViewCommandParser.java
=> Edited Javadoc Comments for ViewCommand(Parser) and minor edits to UG

docs/UserGuide.md
=> Fix hyperlinks for help and clear in UG

docs/UserGuide.md
=> Swap view and reopen in UG

docs/DeveloperGuide.md
=> Add reopen implementation to DG

docs/diagrams/BetterModelClassDiagram.puml
=> Add isFavourite field to Company in class diagram
